project_id = "momi-toast-ingest"

[remotes.dev]
project_id = "xtbraqnlskmqxinjxxdn"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false
sql_paths = []

[edge_runtime]
enabled = true
policy = "per_worker"
deno_version = 2

[functions.toast-orders-webhook-ingest-v1]
verify_jwt = false
