import type { JsonValue } from "./types.ts";

export const draftPath = new URL(
  "../../services/preorder-operations/config/preorder-menu-draft.json",
  import.meta.url,
);

export const base = {
  schema_version: 3,
  publication_ref: "70000000-0000-4000-8000-000000000001",
  publication_mode: "active",
  source_evidence: {
    source_system: "toast",
    menu_id: "fb8d9bc6-42c5-4510-8679-541b363cf597",
    source_version_id: "6".repeat(64),
    observed_at: "2026-07-28T20:00:31.912Z",
  },
  surface: {
    surface_id: "4d933f95-c531-41c5-a162-8a48e450ba70",
    surface_key: "preorder",
    location_id: "2bbf45d0-cc3f-47eb-b697-cb68d0abc123",
    location_name: "Dough Monster",
    timezone: "America/New_York",
    enabled: true,
    freshness_seconds: 300,
    cancellation_policy: {
      summary: "Contact the shop.",
      customer_cancellation_allowed: false,
      customer_modification_allowed: false,
    },
  },
  pickup_policy: {
    horizon_days: 14,
    schedule_mappings: [{ schedule_key: "weekday", iso_weekdays: [1, 2, 3, 4, 5],
      starts_local: "07:00", ends_local: "14:00" },
    { schedule_key: "weekend", iso_weekdays: [6, 7],
      starts_local: "08:00", ends_local: "14:00" }],
    ordering_cutoff: { mode: "previous_day_local_time", local_time: "17:00" },
    closures: [],
  },
  savings_policy: {
    advance_tiers: [],
    quantity_levels: [],
  },
  capacity_policy: { daily_limit: 120, limited_threshold: 24 },
  feature_flags: { checkout: false },
  price_classes: [{
    price_class_key: "classic",
    label: "Classic",
    currency: "USD",
    preorder_price_minor: 150,
    price_floor_minor: 150,
    doughnut_price_class: true,
  }],
  catalog: [{
    item_id: "d11f082b-e0ef-4d6e-9537-45111be658b9",
    item_version: 1,
    category: "Filled Doughnuts",
    name: "Vanilla Joe",
    description: "Espresso creme.",
    currency: "USD",
    shop_price_minor: 250,
    pricing_strategy: "direct_class",
    price_class_key: "classic",
    preorder_price_minor: 150,
    price_floor_minor: 150,
    preorder_enabled: true,
    eligibility_mode: "always",
    eligible_from_date: null,
    eligible_through_date: null,
    media: [],
    allergens: ["milk"],
    allergen_status: "unverified",
    seasonal_eligibility: "eligible",
    available: true,
    maximum_quantity: 24,
    option_groups: [],
    disclosures: [],
  }],
} as JsonValue;
