export const logIntentConfig = {
  version: "momi.communications.log-intent.v1",
  turn: [
    "@log",
    "@log turn",
    "log this",
    "log this bug",
    "log this turn",
    "please log this",
    "please log this bug",
    "please log this turn",
    "can you log this",
    "can you log this bug",
    "can you log this turn",
    "could you log this",
    "could you log this bug",
    "could you log this turn",
    "save this to momi log",
    "save this to the momi log",
  ],
  message: [
    "@log message",
    "log this message",
    "please log this message",
    "can you log this message",
    "could you log this message",
  ],
  conversation: [
    "@log conversation",
    "log this conversation",
    "please log this conversation",
    "can you log this conversation",
    "could you log this conversation",
  ],
} as const
