-- service-owner: toast-data-acquisition

insert into toast_acquisition.operations (
  operation_key, source_operation_id, path_template, resource_type,
  response_kind, pagination_kind, page_size, requires_window,
  exact_resource_only, is_enabled
) values
  ('toast.orders.bulk.v1', 'ordersBulkGet', '/orders/v2/ordersBulk',
    'order', 'collection', 'page', 100, true, false, true),
  ('toast.orders.get.v1', 'ordersGuidGet', '/orders/v2/orders/{guid}',
    'order', 'document', 'none', null, false, true, true),
  ('toast.payments.list.v1', 'paymentsGet', '/orders/v2/payments',
    'payment', 'collection', 'none', null, true, false, true),
  ('toast.payments.get.v1', 'paymentsGuidGet', '/orders/v2/payments/{guid}',
    'payment', 'document', 'none', null, false, true, true),
  ('toast.cash.entries.v1', 'entriesGet', '/cashmgmt/v1/entries',
    'cash_entry', 'collection', 'none', null, true, false, true),
  ('toast.cash.deposits.v1', 'depositsGet', '/cashmgmt/v1/deposits',
    'cash_deposit', 'collection', 'none', null, true, false, true),
  ('toast.restaurants.group.v1', 'groupsManagementGroupGuidRestaurantsGet',
    '/restaurants/v1/groups/{managementGroupGUID}/restaurants',
    'restaurant', 'collection', 'none', null, false, false, true),
  ('toast.restaurants.get.v1', 'restaurantsRestaurantGuidGet',
    '/restaurants/v1/restaurants/{restaurantGUID}',
    'restaurant', 'document', 'none', null, false, false, true),
  ('toast.devices.snapshot.v1', 'getDeviceInfo', '/device-details/v1/device-info',
    'device', 'collection', 'none', null, false, false, true),
  ('toast.kitchen.fulfillments.v1', 'itemFulfillmentsGet',
    '/kitchen/v1/export/itemFulfillments',
    'kitchen_fulfillment', 'collection', 'none', null, true, false, true),
  ('toast.kitchen.prep_stations.v1', 'prepStationsGet',
    '/kitchen/v1/published/prepStations',
    'prep_station', 'collection', 'cursor', null, false, false, true),
  ('toast.kitchen.prep_station.v1', 'prepStationsGuidGet',
    '/kitchen/v1/published/prepStations/{guid}',
    'prep_station', 'document', 'none', null, false, true, true),
  ('toast.labor.employees.v1', 'employeesGet', '/labor/v1/employees',
    'employee', 'collection', 'none', null, false, false, true),
  ('toast.labor.employee.v1', 'employeesEmployeeIdGet',
    '/labor/v1/employees/{employeeId}',
    'employee', 'document', 'none', null, false, true, true),
  ('toast.labor.jobs.v1', 'jobsGet', '/labor/v1/jobs',
    'job', 'collection', 'none', null, false, false, true),
  ('toast.labor.job.v1', 'jobsJobIdGet', '/labor/v1/jobs/{jobId}',
    'job', 'document', 'none', null, false, true, true),
  ('toast.labor.shifts.v1', 'shiftsGet', '/labor/v1/shifts',
    'shift', 'collection', 'none', null, true, false, true),
  ('toast.labor.shift.v1', 'shiftsShiftIdGet', '/labor/v1/shifts/{shiftId}',
    'shift', 'document', 'none', null, false, true, true),
  ('toast.labor.time_entries.v1', 'timeEntriesGet', '/labor/v1/timeEntries',
    'time_entry', 'collection', 'none', null, true, false, true),
  ('toast.labor.time_entry.v1', 'timeEntriesTimeEntryIdGet',
    '/labor/v1/timeEntries/{timeEntryId}',
    'time_entry', 'document', 'none', null, false, true, true),
  ('toast.menus.full.v1', 'menusGet', '/menus/v2/menus',
    'menu', 'document', 'none', null, false, false, true),
  ('toast.menus.metadata.v1', 'metadataGet', '/menus/v2/metadata',
    'menu_metadata', 'document', 'none', null, false, false, true),
  ('toast.packaging.snapshot.v1', 'getPackagingConfig',
    '/packaging/v1/published/packagingConfig',
    'packaging', 'document', 'none', null, false, false, true),
  ('toast.availability.snapshot.v1', 'availabilityGet',
    '/restaurant-availability/v1/availability',
    'restaurant_availability', 'document', 'none', null, false, false, true),
  ('toast.ordering_schedule.snapshot.v1', 'orderingScheduleGet',
    '/ordermgmt-config/v1/published/orderingSchedule',
    'ordering_schedule', 'document', 'none', null, false, false, true),
  ('toast.stock.snapshot.v1', 'getInventory', '/stock/v1/inventory',
    'stock_state', 'collection', 'none', null, false, false, true);
