import { DEADMAN_GENERATION_PREFIX,
  DEADMAN_TERMINAL_MARKER } from "./deadman_command_constants.ts"
import { EXPECTED_GUARD_NAME } from "./sample_constants.ts"

export const DEADMAN_RECONCILIATION_GUARD_SQL = [
  "guard_rows as (",
  "  select j.jobid, j.jobname, j.schedule, j.active,",
  "    encode(extensions.digest(convert_to(j.command, 'UTF8'), 'sha256'), 'hex')",
  "      as command_sha256, md5(j.command) as command_md5,",
  "    (regexp_match(j.command, '''(run-[a-f0-9-]{8,64})''::text as run_id'))[1]",
  "      as run_id,",
  "    (regexp_match(j.command, '''([a-f0-9]{64})''::text as generation_sha256'))[1]",
  "      as generation_sha256,",
  "    (regexp_match(j.command, '''([^'']+)''::text as expiry_utc'))[1] as expiry_utc,",
  "    ((regexp_match(j.command, '([0-9]+)::bigint as guard_run_id'))[1])::bigint",
  "      as terminal_guard_run_id,",
  "    (regexp_match(j.command, '''([^'']+)''::text as guard_start_utc'))[1]",
  "      as terminal_guard_start_utc,",
  "    (regexp_match(j.command, '''([^'']+)''::text as expected_terminal_status'))[1]",
  "      as terminal_expected_status,",
  "    ((regexp_match(j.command, '([0-9]+)::integer as exact_identity_mask'))[1])::integer",
  "      as exact_identity_mask,",
  "    ((regexp_match(j.command, '([0-9]+)::integer as active_before_mask'))[1])::integer",
  "      as active_before_mask,",
  "    ((regexp_match(j.command, '([0-9]+)::integer as inactive_after_mask'))[1])::integer",
  "      as inactive_after_mask,",
  "    (regexp_match(j.command, '''([a-f0-9]{64})''::text as original_command_sha256'))[1]",
  "      as original_command_sha256,",
  "    (regexp_match(j.command, '''([a-f0-9]{32})''::text as original_command_md5'))[1]",
  "      as original_command_md5",
  `  from cron.job j where j.jobname = '${EXPECTED_GUARD_NAME}'`,
  `    and position('${DEADMAN_TERMINAL_MARKER}' in j.command) > 0`,
  "),",
  "guard_summary as (",
  "  select count(*)::bigint as identity_count from guard_rows",
  "),",
  "guard_selected as (",
  "  select g.* from guard_rows g cross join guard_summary s",
  "  where s.identity_count = 1",
  "),",
  "terminal_history as (",
  "  select r.* from run_window r join guard_selected g",
  "    on r.jobid = g.jobid and r.runid = g.terminal_guard_run_id",
  "),",
  "guard_history as (",
  "  select coalesce(max(r.runid), 0)::bigint as maximum_run_id,",
  "    coalesce(max(r.runid) filter (where r.status = 'succeeded'), 0)::bigint",
  "      as maximum_success_run_id,",
  "    coalesce(max(r.runid) filter (where r.status <> 'succeeded'), 0)::bigint",
  "      as maximum_failure_run_id,",
  "    count(*) filter (where r.status = 'succeeded'",
  "      and r.runid = (select terminal_guard_run_id from guard_selected)",
  "      and r.start_time = (select terminal_guard_start_utc::timestamptz",
  "        from guard_selected)",
  "      and r.start_time >= (select expiry_utc::timestamptz from guard_selected)",
  "      and r.start_time <= (select expiry_utc::timestamptz + interval '5 seconds'",
  "        from guard_selected)",
  "      and r.command_sha256 = (select original_command_sha256 from guard_selected)",
  "      and r.command_md5 = (select original_command_md5 from guard_selected))::bigint",
  "      as successful_terminal_run_count,",
  "    count(*) filter (where r.status <> 'succeeded')::bigint",
  "      as terminal_failure_count,",
  "    max(r.start_time) filter (where r.runid =",
  "      (select terminal_guard_run_id from guard_selected))",
  "      as terminal_history_start_time,",
  "    max(r.status) filter (where r.runid =",
  "      (select terminal_guard_run_id from guard_selected))",
  "      as terminal_history_status",
  "  from terminal_history r",
  "),",
  "deadman_history as (",
  "  select coalesce(max(r.runid), 0)::bigint as maximum_run_id",
  "  from run_window r",
  `  where position('${DEADMAN_GENERATION_PREFIX}:' in r.command) > 0`,
  "),",
] as const
