import { DEADMAN_EXPIRY_PLACEHOLDER } from "./deadman_command_constants.ts"
import { generateDeadmanCommand } from "./generate_deadman_command.ts"
import { GUARD_BOOTSTRAP_LOCK_TIMEOUT, GUARD_BOOTSTRAP_STATEMENT_TIMEOUT } from "./guard_bootstrap_constants.ts"
import { CURRENT_DEADMAN_TEMPLATE_TAG, GUARD_HEARTBEAT_DO_TAG, GUARD_HEARTBEAT_MARKER, NEXT_DEADMAN_TEMPLATE_TAG } from "./guard_heartbeat_constants.ts"
import { CRON_RUN_EVIDENCE_WINDOW_ROWS } from "./sample_constants.ts"
import { SQL_SCHEMA_VERSION } from "./sql_artifact_constants.ts"
import { validateGuardHeartbeatInput } from "./validate_guard_heartbeat_input.ts"

export function generateGuardHeartbeatSql(value: unknown): string {
  const input = validateGuardHeartbeatInput(value)
  const currentTemplate = generateDeadmanCommand({
    runId: input.runId, generationSha256: input.currentGenerationSha256,
    startCronRunId: input.startCronRunId, guardName: input.guardName,
    guardSchedule: input.guardSchedule, targetJobs: input.targetJobs,
    advisoryLockKey: input.advisoryLockKey,
    expiryPlaceholder: DEADMAN_EXPIRY_PLACEHOLDER,
  })
  const tags = [GUARD_HEARTBEAT_DO_TAG, CURRENT_DEADMAN_TEMPLATE_TAG, NEXT_DEADMAN_TEMPLATE_TAG]
  if (tags.some((tag) => currentTemplate.includes(tag) || input.nextDeadmanCommand.includes(tag))) {
    throw new Error("Guard heartbeat SQL delimiter collision")
  }
  const currentMarker = `momi:deadman:generation:${input.runId}:${input.currentGenerationSha256}`
  const nextMarker = `momi:deadman:generation:${input.runId}:${input.nextGenerationSha256}`
  const targetCases = input.targetJobs.map((job) => [
    `    when ${job.jobId} then j.jobname = '${job.jobName}' and`,
    `      j.schedule = '${job.schedule}' and md5(j.command) = '${job.commandMd5}'`,
  ].join("\n")).join("\n")
  return [
    "begin;",
    `set local statement_timeout = '${GUARD_BOOTSTRAP_STATEMENT_TIMEOUT}';`,
    `set local lock_timeout = '${GUARD_BOOTSTRAP_LOCK_TIMEOUT}';`,
    `do ${GUARD_HEARTBEAT_DO_TAG}`,
    "declare",
    "  lock_acquired boolean; guard_count bigint; current_command text;",
    "  current_name text; current_schedule text; current_active boolean;",
    "  current_expiry_utc text; current_expiry_at timestamptz;",
    "  identities_match boolean; targets_active boolean; latest_run_id bigint;",
    "  final_run_id bigint; target_executions bigint;",
    "  database_now timestamptz; next_expiry_at timestamptz; next_expiry_utc text;",
    `  current_template constant text := ${CURRENT_DEADMAN_TEMPLATE_TAG}${currentTemplate}${CURRENT_DEADMAN_TEMPLATE_TAG};`,
    `  next_template constant text := ${NEXT_DEADMAN_TEMPLATE_TAG}${input.nextDeadmanCommand}${NEXT_DEADMAN_TEMPLATE_TAG};`,
    "  materialized_next text; readback_command text; readback_active boolean;",
    "  readback_name text; readback_schedule text;",
    "begin",
    `  select pg_try_advisory_xact_lock(hashtextextended('${input.advisoryLockKey}', 0))`,
    "    into lock_acquired;",
    "  if not lock_acquired then raise exception 'momi_guard_heartbeat_lock_unavailable'; end if;",
    "  select count(*) into guard_count from cron.job",
    `    where jobname = '${input.guardName}';`,
    "  if guard_count <> 1 then raise exception 'momi_guard_heartbeat_guard_identity'; end if;",
    "  select j.jobname, j.schedule, j.active, j.command",
    "  into strict current_name, current_schedule, current_active, current_command",
    `  from cron.job j where j.jobid = ${input.guardJobId};`,
    `  if current_name <> '${input.guardName}' or current_schedule <> '${input.guardSchedule}' then`,
    "    raise exception 'momi_guard_heartbeat_guard_identity'; end if;",
    "  if not current_active then raise exception 'momi_guard_heartbeat_guard_inactive'; end if;",
    "  current_expiry_utc := substring(current_command from 'expiry_at constant timestamptz := timestamptz ''([^'']+)''');",
    "  if current_expiry_utc is null or current_expiry_utc !~",
    "      '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{6}Z$' then",
    "    raise exception 'momi_guard_heartbeat_current_command'; end if;",
    "  current_expiry_at := current_expiry_utc::timestamptz;",
    "  if current_command <> replace(current_template,",
    `      '${DEADMAN_EXPIRY_PLACEHOLDER}', current_expiry_utc)`,
    `      or position('${currentMarker}' in current_command) = 0`,
    `      or to_char(current_expiry_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')`,
    "        <> current_expiry_utc then",
    "    raise exception 'momi_guard_heartbeat_current_command'; end if;",
    "  perform 1 from cron.job where jobid in (2, 3, 4, 11);",
    "  select count(*) = 4 and bool_and(case j.jobid",
    targetCases,
    "    else false end), coalesce(bool_or(j.active), false)",
    "  into identities_match, targets_active from cron.job j",
    "  where j.jobid in (2, 3, 4, 11);",
    "  if not coalesce(identities_match, false) then",
    "    raise exception 'momi_guard_heartbeat_target_identity'; end if;",
    "  if targets_active then raise exception 'momi_guard_heartbeat_target_active'; end if;",
    "  select coalesce(max(runid), 0)::bigint into latest_run_id",
    "    from cron.job_run_details;",
    `  if latest_run_id < ${input.startCronRunId}`,
    `      or latest_run_id - ${input.startCronRunId} > ${CRON_RUN_EVIDENCE_WINDOW_ROWS} then`,
    "    raise exception 'momi_guard_heartbeat_history_gap'; end if;",
    "  select count(*) into target_executions from cron.job_run_details",
    `  where runid > ${input.startCronRunId} and runid <= latest_run_id`,
    "    and jobid in (2, 3, 4, 11);",
    "  if target_executions <> 0 then raise exception 'momi_guard_heartbeat_target_running'; end if;",
    `  if length(next_template) - length(replace(next_template, '${DEADMAN_EXPIRY_PLACEHOLDER}', ''))`,
    `      <> length('${DEADMAN_EXPIRY_PLACEHOLDER}') then`,
    "    raise exception 'momi_guard_heartbeat_placeholder'; end if;",
    "  select clock_timestamp() into database_now;",
    "  if current_expiry_at <= database_now then raise exception 'momi_guard_heartbeat_expired'; end if;",
    "  next_expiry_at := database_now + interval '30 seconds';",
    `  next_expiry_utc := to_char(next_expiry_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"');`,
    `  materialized_next := replace(next_template, '${DEADMAN_EXPIRY_PLACEHOLDER}', next_expiry_utc);`,
    `  if position('${DEADMAN_EXPIRY_PLACEHOLDER}' in materialized_next) <> 0 then`,
    "    raise exception 'momi_guard_heartbeat_materialization'; end if;",
    `  perform cron.alter_job(job_id := ${input.guardJobId}, command := materialized_next);`,
    "  select coalesce(max(runid), 0)::bigint into final_run_id",
    "    from cron.job_run_details;",
    `  if final_run_id < latest_run_id or final_run_id - ${input.startCronRunId}`,
    `      > ${CRON_RUN_EVIDENCE_WINDOW_ROWS} then`,
    "    raise exception 'momi_guard_heartbeat_history_gap'; end if;",
    "  select count(*) into target_executions from cron.job_run_details",
    `  where runid > ${input.startCronRunId} and runid <= final_run_id`,
    "    and jobid in (2, 3, 4, 11);",
    "  if target_executions <> 0 then raise exception 'momi_guard_heartbeat_target_running'; end if;",
    "  select count(*) = 4 and bool_and(case j.jobid",
    targetCases,
    "    else false end), coalesce(bool_or(j.active), false)",
    "  into identities_match, targets_active from cron.job j",
    "  where j.jobid in (2, 3, 4, 11);",
    "  if not coalesce(identities_match, false) then",
    "    raise exception 'momi_guard_heartbeat_target_identity'; end if;",
    "  if targets_active then raise exception 'momi_guard_heartbeat_target_active'; end if;",
    "  select j.jobname, j.schedule, j.active, j.command",
    "  into strict readback_name, readback_schedule, readback_active, readback_command",
    `  from cron.job j where j.jobid = ${input.guardJobId};`,
    `  if readback_name <> '${input.guardName}' or readback_schedule <> '${input.guardSchedule}'`,
    "      or not readback_active or readback_command <> materialized_next",
    `      or position('${nextMarker}' in readback_command) = 0`,
    "      or position(next_expiry_utc in readback_command) = 0 then",
    "    raise exception 'momi_guard_heartbeat_readback'; end if;",
    "end",
    `${GUARD_HEARTBEAT_DO_TAG};`,
    `select '${GUARD_HEARTBEAT_MARKER}'::text as marker,`,
    `  ${SQL_SCHEMA_VERSION}::integer as schema_version, jsonb_build_object(`,
    `    'guardJobId', j.jobid, 'guardName', j.jobname, 'guardSchedule', j.schedule,`,
    `    'guardActive', j.active, 'runId', '${input.runId}',`,
    `    'previousGenerationSha256', '${input.currentGenerationSha256}',`,
    `    'nextGenerationSha256', '${input.nextGenerationSha256}',`,
    "    'expiryUtc', substring(j.command from 'expiry_at constant timestamptz := timestamptz ''([^'']+)'''),",
    "    'commandSha256', encode(extensions.digest(",
    "      convert_to(j.command, 'UTF8'), 'sha256'), 'hex'),",
    "    'commandMd5', md5(j.command)) as sample",
    `from cron.job j where j.jobid = ${input.guardJobId};`,
    "commit;",
    "",
  ].join("\n")
}
