import { DEADMAN_ADVISORY_LOCK_KEY } from "./deadman_command_constants.ts"
import type { GuardBootstrapResult } from "./guard_bootstrap_types.ts"
import { loadRecoverySnapshotSql } from "./load_recovery_snapshot_sql.ts"
import { RECOVERY_ACTIVATION_MARKER } from "./recovery_constants.ts"
import { EXPECTED_GUARD_NAME, EXPECTED_GUARD_SCHEDULE, EXPECTED_TARGET_JOBS,
  MAX_ACTIVE_CRON_EXECUTIONS, MAX_DATABASE_BACKENDS_EXCLUSIVE,
  MAX_WAL_DIRECTORY_BYTES_EXCLUSIVE } from "./sample_constants.ts"
import { SQL_SCHEMA_VERSION } from "./sql_artifact_constants.ts"

export function generateRecoveryActivationSql(guard: GuardBootstrapResult): string {
  if (!Number.isSafeInteger(guard.guardJobId) || guard.guardJobId < 1 ||
    !/^[a-f0-9]{64}$/.test(guard.generationSha256) ||
    !/^[a-f0-9]{64}$/.test(guard.commandSha256)) throw new Error("Activation input is invalid")
  const snapshot = loadRecoverySnapshotSql().trimEnd().slice(0, -1).replace(/^/gm, "    ")
  const identities = EXPECTED_TARGET_JOBS.map((job) =>
    `(jobid = ${job.jobId} and jobname = '${job.jobName}' and schedule = '${job.schedule}' and md5(command) = '${job.commandMd5}')`,
  ).join(" or ")
  const invalidFields = [
    "toastRunning", "toastRetry", "toastDead", "toastFuture", "toastAttempted",
    "toastUnexpected", "toastPartial", "toastUnmatched", "routingRunning",
    "routingRetry", "routingDead", "routingInvalid", "deliveryRunning",
    "deliveryRetry", "deliveryDead", "deliveryInvalid", "queueDead", "openAttempts",
    "projectionReservations", "expiredLeases", "longLeases", "workerCapViolations",
    "waitingLocks", "cohortDead", "cohortRetry", "cohortInvalid", "cohortAmbiguous",
    "cohortMissingPriorMemberCount", "cohortMissingPriorLineageEdgeCount",
    "cohortChangedParentCount",
  ].map((key) => `(frozen_sample->>'${key}')::bigint <> 0`).join(" or ")
  return [
    "begin;", "set local statement_timeout = '12s';", "set local lock_timeout = '2s';",
    "do $momi_recovery_activation$", "declare",
    "  lock_acquired boolean; frozen_sample jsonb; guard_command text; guard_expiry timestamptz;",
    "  started_at timestamptz; identities_match boolean; active_mask integer;",
    "begin",
    `  select pg_try_advisory_xact_lock(hashtextextended('${DEADMAN_ADVISORY_LOCK_KEY}', 0)) into lock_acquired;`,
    "  if not lock_acquired then raise exception 'momi_recovery_activation_lock'; end if;",
    `  select command into strict guard_command from cron.job where jobid = ${guard.guardJobId}`,
    `    and jobname = '${EXPECTED_GUARD_NAME}' and schedule = '${EXPECTED_GUARD_SCHEDULE}' and active;`,
    `  if encode(extensions.digest(convert_to(guard_command, 'UTF8'), 'sha256'), 'hex') <> '${guard.commandSha256}'`,
    `      or position('momi:deadman:generation:${guard.runId}:${guard.generationSha256}' in guard_command) = 0 then`,
    "    raise exception 'momi_recovery_activation_generation'; end if;",
    "  guard_expiry := substring(guard_command from 'expiry_at constant timestamptz := timestamptz ''([^'']+)''')::timestamptz;",
    "  if guard_expiry <= clock_timestamp() then raise exception 'momi_recovery_activation_expired'; end if;",
    `  select count(*) = 4 and bool_and(${identities}), sum(case when active then 1 else 0 end)::integer`,
    "    into identities_match, active_mask from cron.job where jobid in (2, 3, 4, 11);",
    "  if not coalesce(identities_match, false) or active_mask <> 0 then",
    "    raise exception 'momi_recovery_activation_target_state'; end if;",
    "  select sample into strict frozen_sample from (", snapshot, "  ) recovery_snapshot;",
    "  started_at := to_timestamp((frozen_sample->>'observedAtUtcMs')::bigint / 1000.0);",
    "  if (frozen_sample->>'cohortStartedAtUtcMs')::bigint",
    "      <> (frozen_sample->>'observedAtUtcMs')::bigint",
    "      or (frozen_sample->>'cohortJobOpen')::bigint <> (frozen_sample->>'toastOpen')::bigint",
    "      or (frozen_sample->>'cohortRoutingOpen')::bigint <> (frozen_sample->>'routingOpen')::bigint",
    "      or (frozen_sample->>'cohortDeliveryOpen')::bigint <> (frozen_sample->>'deliveryOpen')::bigint",
    "      or (frozen_sample->>'cohortQueueOpen')::bigint <> (frozen_sample->>'queueReady')::bigint then",
    "    raise exception 'momi_recovery_activation_cohort'; end if;",
    "  if (frozen_sample->>'toastOpen')::bigint <> (frozen_sample->>'toastReady')::bigint",
    "      or (frozen_sample->>'routingOpen')::bigint <> (frozen_sample->>'routingReady')::bigint",
    "      or (frozen_sample->>'deliveryOpen')::bigint <> (frozen_sample->>'deliveryReady')::bigint",
    `      or ${invalidFields} then raise exception 'momi_recovery_activation_work'; end if;`,
    "  if (frozen_sample->>'guardIdentityCount')::bigint <> 1",
    "      or (frozen_sample->>'activeToastRouteCount')::bigint <> 1",
    "      or (frozen_sample->>'activeRoutingRouteCount')::bigint <> 1",
    "      or (frozen_sample->>'activeProjectionEdgeRouteCount')::bigint <> 0",
    "      or (frozen_sample->>'databaseProjectionModeCount')::bigint <> 1",
    "      or (frozen_sample->>'activeProjectionSubscriptionCount')::bigint <> 1",
    "      or (frozen_sample->>'routeContractViolations')::bigint <> 0 then",
    "    raise exception 'momi_recovery_activation_routes'; end if;",
    `  if (frozen_sample->>'activeCronExecutions')::bigint > ${MAX_ACTIVE_CRON_EXECUTIONS}`,
    `      or (frozen_sample->>'databaseBackends')::bigint >= ${MAX_DATABASE_BACKENDS_EXCLUSIVE}`,
    `      or (frozen_sample->>'walDirectoryBytes')::bigint >= ${MAX_WAL_DIRECTORY_BYTES_EXCLUSIVE}`,
    "      or (frozen_sample->>'maxConnections')::bigint",
    "        - (frozen_sample->>'reservedConnections')::bigint",
    "        - (frozen_sample->>'databaseBackends')::bigint < 8",
    "      or (frozen_sample->>'registryCount')::bigint < 1",
    "      or (frozen_sample->>'registryContractViolations')::bigint <> 0 then",
    "    raise exception 'momi_recovery_activation_capacity'; end if;",
    "  perform set_config('momi.recovery_frozen', frozen_sample::text, true);",
    "  perform set_config('momi.recovery_started_at',",
    "    to_char(started_at at time zone 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"'), true);",
    `  select command into strict guard_command from cron.job where jobid = ${guard.guardJobId}`,
    `    and jobname = '${EXPECTED_GUARD_NAME}' and schedule = '${EXPECTED_GUARD_SCHEDULE}' and active;`,
    `  if encode(extensions.digest(convert_to(guard_command, 'UTF8'), 'sha256'), 'hex') <> '${guard.commandSha256}' then`,
    "    raise exception 'momi_recovery_activation_generation'; end if;",
    "  guard_expiry := substring(guard_command from 'expiry_at constant timestamptz := timestamptz ''([^'']+)''')::timestamptz;",
    "  if guard_expiry <= clock_timestamp() then raise exception 'momi_recovery_activation_expired'; end if;",
    `  select count(*) = 4 and bool_and(${identities}), sum(case when active then 1 else 0 end)::integer`,
    "    into identities_match, active_mask from cron.job where jobid in (2, 3, 4, 11);",
    "  if not coalesce(identities_match, false) or active_mask <> 0 then",
    "    raise exception 'momi_recovery_activation_target_state'; end if;",
    "  perform cron.alter_job(job_id := 11, active := true);",
    "  perform cron.alter_job(job_id := 2, active := true);",
    "  perform cron.alter_job(job_id := 3, active := true);",
    "  select sum(case when active then jobid else 0 end)::integer into active_mask",
    "    from cron.job where jobid in (2, 3, 4, 11);",
    "  if active_mask <> 16 then raise exception 'momi_recovery_activation_readback'; end if;",
    `  if (select encode(extensions.digest(convert_to(command, 'UTF8'), 'sha256'), 'hex') from cron.job where jobid = ${guard.guardJobId}) <> '${guard.commandSha256}' then`,
    "    raise exception 'momi_recovery_activation_guard_drift'; end if;",
    "end", "$momi_recovery_activation$;",
    "with target_state as (select jsonb_agg(jsonb_build_object('jobId', jobid,",
    "  'jobName', jobname, 'schedule', schedule, 'commandMd5', md5(command),",
    "  'active', active) order by jobid) jobs from cron.job where jobid in (2,3,4,11))",
    `select '${RECOVERY_ACTIVATION_MARKER}'::text marker, ${SQL_SCHEMA_VERSION}::integer schema_version,`,
    "  jsonb_build_object('startedAtUtcMs', floor(extract(epoch from current_setting('momi.recovery_started_at')::timestamptz) * 1000)::bigint,",
    "    'frozen', current_setting('momi.recovery_frozen')::jsonb, 'targetJobs', t.jobs,",
    `    'guardJobId', ${guard.guardJobId}, 'generationSha256', '${guard.generationSha256}',`,
    `    'guardCommandSha256', '${guard.commandSha256}') sample from target_state t;`,
    "commit;", "",
  ].join("\n")
}
