export const PROGRAM_EXIT_SUCCESS = 0
export const PROGRAM_EXIT_PRE_GUARD = 20
export const PROGRAM_EXIT_RECOVERED_UNSUCCESSFUL = 30
export const PROGRAM_EXIT_MANUAL = 40

export const PROGRAM_STDERR_PRE_GUARD = "PRE_GUARD_FAILURE"
export const PROGRAM_STDERR_RECOVERED = "RECOVERED_BUT_UNSUCCESSFUL"
export const PROGRAM_STDERR_MANUAL = "MANUAL_RECONCILIATION_REQUIRED"
