import type { RecoverySnapshot } from "./recovery_types.ts"

export function buildRecoveryClassificationCohortEvidence(sample: RecoverySnapshot): unknown {
  return { observed_at_utc: new Date(sample.observedAtUtcMs).toISOString(),
    started_at_utc: new Date(sample.cohortStartedAtUtcMs).toISOString(),
    job_high_water: sample.jobHighWater, observation_high_water: sample.observationHighWater,
    due_occurrence_count: sample.dueOccurrences.length,
    due_schedule_count: sample.dueScheduleCount,
    boundary_sha256: sample.cohortBoundarySha256,
    root_count: sample.cohortRootCount, root_sha256: sample.cohortRootSha256,
    toast_root_count: sample.toastRootCount, toast_root_sha256: sample.toastRootSha256,
    routing_root_count: sample.routingRootCount,
    routing_root_sha256: sample.routingRootSha256,
    delivery_root_count: sample.deliveryRootCount,
    delivery_root_sha256: sample.deliveryRootSha256,
    queue_mapping_count: sample.queueMappingCount,
    queue_mapping_sha256: sample.queueMappingSha256,
    membership_count: sample.cohortMembershipCount,
    membership_sha256: sample.cohortMembershipSha256,
    prior_membership_count: sample.priorCohortMembershipCount,
    prior_membership_sha256: sample.priorCohortMembershipSha256,
    membership_addition_count: sample.cohortMembershipAdditionCount,
    membership_addition_sha256: sample.cohortMembershipAdditionSha256,
    missing_prior_member_count: sample.cohortMissingPriorMemberCount,
    missing_prior_member_sha256: sample.cohortMissingPriorMemberSha256,
    lineage_edge_count: sample.cohortLineageEdgeCount,
    lineage_edge_sha256: sample.cohortLineageEdgeSha256,
    missing_prior_lineage_edge_count: sample.cohortMissingPriorLineageEdgeCount,
    missing_prior_lineage_edge_sha256: sample.cohortMissingPriorLineageEdgeSha256,
    changed_parent_count: sample.cohortChangedParentCount,
    changed_parent_sha256: sample.cohortChangedParentSha256,
    job_count: sample.cohortJobCount, job_open: sample.cohortJobOpen,
    attempt_count: sample.cohortAttemptCount, attempt_open: sample.cohortAttemptOpen,
    observation_count: sample.cohortObservationCount, event_count: sample.cohortEventCount,
    routing_count: sample.cohortRoutingCount, routing_open: sample.cohortRoutingOpen,
    delivery_count: sample.cohortDeliveryCount, delivery_open: sample.cohortDeliveryOpen,
    queue_open: sample.cohortQueueOpen, reservation_open: sample.cohortReservationOpen,
    dead: sample.cohortDead, retry: sample.cohortRetry,
    invalid: sample.cohortInvalid, ambiguous: sample.cohortAmbiguous,
    emittable_parents: sample.cohortEmittableParents,
    terminal_count: sample.cohortTerminalCount }
}
