import {
  GUARD_BOOTSTRAP_LOCK_TIMEOUT,
  GUARD_BOOTSTRAP_STATEMENT_TIMEOUT,
} from "./guard_bootstrap_constants.ts"
import {
  ROLLBACK_DO_TAG,
  ROLLBACK_MARKER,
} from "./recovery_control_constants.ts"
import { SQL_SCHEMA_VERSION } from "./sql_artifact_constants.ts"
import { validateRecoveryControlInput } from "./validate_recovery_control_input.ts"

export function generateRollbackSql(value: unknown): string {
  const input = validateRecoveryControlInput(value)
  const names = input.targetJobs.map((job) => `'${job.jobName}'`).join(", ")
  const cases = input.targetJobs.map((job) => [
    `    when ${job.jobId} then j.jobname = '${job.jobName}' and`,
    `      j.schedule = '${job.schedule}' and md5(j.command) = '${job.commandMd5}'`,
  ].join("\n")).join("\n")
  return [
    "begin;",
    `set local statement_timeout = '${GUARD_BOOTSTRAP_STATEMENT_TIMEOUT}';`,
    `set local lock_timeout = '${GUARD_BOOTSTRAP_LOCK_TIMEOUT}';`,
    `do ${ROLLBACK_DO_TAG}`,
    "declare",
    "  lock_acquired boolean; targets_match boolean; target_name_count bigint;",
    "  guard_name_count bigint; guard_id_count bigint; guard_active boolean;",
    "  guard_name text; guard_schedule text;",
    "begin",
    `  select pg_try_advisory_xact_lock(hashtextextended('${input.advisoryLockKey}', 0))`,
    "    into lock_acquired;",
    "  if not lock_acquired then raise exception 'momi_rollback_lock_unavailable'; end if;",
    "  perform 1 from cron.job where jobid in (2, 3, 4, 11) for update;",
    "  select count(*) = 4 and bool_and(case j.jobid",
    cases,
    "    else false end) into targets_match",
    "  from cron.job j where j.jobid in (2, 3, 4, 11);",
    `  select count(*) into target_name_count from cron.job where jobname in (${names});`,
    "  if not coalesce(targets_match, false) or target_name_count <> 4 then",
    "    raise exception 'momi_rollback_target_identity'; end if;",
    `  select count(*) into guard_name_count from cron.job where jobname = '${input.guardName}';`,
    `  select count(*) into guard_id_count from cron.job where jobid = ${input.guardJobId};`,
    "  if guard_name_count = 0 and guard_id_count = 0 then",
    "    guard_active := false;",
    "  elsif guard_name_count = 1 and guard_id_count = 1 then",
    "    select j.jobname, j.schedule, j.active",
    "    into strict guard_name, guard_schedule, guard_active",
    `    from cron.job j where j.jobid = ${input.guardJobId} for update;`,
    `    if guard_name <> '${input.guardName}' or guard_schedule <> '${input.guardSchedule}' then`,
    "      raise exception 'momi_rollback_guard_identity'; end if;",
    "  else raise exception 'momi_rollback_guard_identity';",
    "  end if;",
    "  perform cron.alter_job(job_id := 3, active := false);",
    "  perform cron.alter_job(job_id := 2, active := false);",
    "  perform cron.alter_job(job_id := 11, active := false);",
    "  perform cron.alter_job(job_id := 4, active := false);",
    "  if exists (select 1 from cron.job where jobid in (2, 3, 4, 11) and active) then",
    "    raise exception 'momi_rollback_target_readback'; end if;",
    "  if guard_name_count = 1 and guard_active then",
    `    perform cron.alter_job(job_id := ${input.guardJobId}, active := false);`,
    "  end if;",
    "  if guard_name_count = 1 and not exists (select 1 from cron.job",
    `      where jobid = ${input.guardJobId} and jobname = '${input.guardName}'`,
    `        and schedule = '${input.guardSchedule}' and not active) then`,
    "    raise exception 'momi_rollback_guard_readback'; end if;",
    "end",
    `${ROLLBACK_DO_TAG};`,
    "with target_state as (",
    "  select jsonb_agg(jsonb_build_object(",
    "    'jobId', j.jobid, 'jobName', j.jobname, 'schedule', j.schedule,",
    "    'commandMd5', md5(j.command), 'active', j.active) order by j.jobid) as jobs",
    "  from cron.job j where j.jobid in (2, 3, 4, 11)",
    "), guard_state as (",
    `  select count(*)::bigint as rows, coalesce(min(jobid), 0)::bigint as jobid`,
    `  from cron.job where jobid = ${input.guardJobId} or jobname = '${input.guardName}'`,
    ")",
    `select '${ROLLBACK_MARKER}'::text as marker, ${SQL_SCHEMA_VERSION}::integer as schema_version,`,
    "  jsonb_build_object('targetJobs', t.jobs, 'guardIdentityCount', g.rows,",
    "    'guardPresent', g.rows = 1,",
    "    'guardJobId', case when g.rows = 1 then g.jobid else 0 end,",
    "    'guard', case when g.rows = 1 then (select jsonb_build_object(",
    "      'jobName', j.jobname, 'schedule', j.schedule, 'active', j.active)",
    "      from cron.job j where j.jobid = g.jobid) else jsonb_build_object(",
    `      'jobName', '${input.guardName}', 'schedule', '${input.guardSchedule}', 'active', false) end,`,
    "    'guardState', case when g.rows = 1 then 'guard_inactive' else 'guard_absent' end",
    "  ) as sample from target_state t cross join guard_state g;",
    "commit;",
    "",
  ].join("\n")
}
