import { DEADMAN_RECONCILIATION_MARKER,
  DEADMAN_RECONCILIATION_SQL_SHA256 } from "./deadman_reconciliation_constants.ts"
import { DEADMAN_RECONCILIATION_GUARD_SQL } from "./deadman_reconciliation_guard_sql.ts"
import { loadCombinedSampleArtifact } from "./load_combined_sample_artifact.ts"
import { SQL_SCHEMA_VERSION } from "./sql_artifact_constants.ts"
import { sha256Text } from "./sha256_text.ts"

export function generateDeadmanReconciliationSql(): string {
  const fastSql = loadCombinedSampleArtifact("fast").replace(/^/gm, "  ")
  const sql = [
    "with heartbeat_clock as (",
    "  select clock_timestamp() as observed_at",
    "),",
    "latest_run as (",
    "  select coalesce(max(runid), 0)::bigint as runid from cron.job_run_details",
    "),",
    "run_window as (",
    "  select d.runid, d.jobid, d.status, d.start_time, d.command,",
    "    encode(extensions.digest(convert_to(d.command, 'UTF8'), 'sha256'), 'hex')",
    "      as command_sha256, md5(d.command) as command_md5",
    "  from cron.job_run_details d cross join latest_run l",
    "  where d.runid > greatest(l.runid - 16384, 0)",
    "),",
    ...DEADMAN_RECONCILIATION_GUARD_SQL,
    "fast_envelope as (",
    fastSql,
    ")",
    "select",
    `  '${DEADMAN_RECONCILIATION_MARKER}'::text as marker,`,
    `  ${SQL_SCHEMA_VERSION}::integer as schema_version,`,
    "  jsonb_build_object(",
    "    'observedAtUtcMs', floor(extract(epoch from c.observed_at) * 1000)::bigint,",
    "    'currentMaxRunId', l.runid,",
    "    'coveredAfterRunId', greatest(l.runid - 16384, 0),",
    "    'guardIdentityCount', s.identity_count,",
    "    'guardJobId', case when s.identity_count = 1 then g.jobid else 0 end,",
    "    'guardName', case when s.identity_count = 1 then g.jobname else null end,",
    "    'guardSchedule', case when s.identity_count = 1 then g.schedule else null end,",
    "    'guardActive', case when s.identity_count = 1 then g.active else null end,",
    "    'runId', case when s.identity_count = 1 then g.run_id else null end,",
    "    'generationSha256', case when s.identity_count = 1",
    "      then g.generation_sha256 else null end,",
    "    'expiryUtc', case when s.identity_count = 1 then g.expiry_utc else null end,",
    "    'terminalCommandSha256', case when s.identity_count = 1",
    "      then g.command_sha256 else null end,",
    "    'terminalCommandMd5', case when s.identity_count = 1",
    "      then g.command_md5 else null end,",
    "    'terminalGuardRunId', case when s.identity_count = 1",
    "      then g.terminal_guard_run_id else 0 end,",
    "    'terminalGuardStartUtc', case when s.identity_count = 1",
    "      then g.terminal_guard_start_utc else null end,",
    "    'terminalExpectedStatus', case when s.identity_count = 1",
    "      then g.terminal_expected_status else null end,",
    "    'exactIdentityMask', case when s.identity_count = 1",
    "      then g.exact_identity_mask else 0 end,",
    "    'activeBeforeMask', case when s.identity_count = 1",
    "      then g.active_before_mask else 0 end,",
    "    'inactiveAfterMask', case when s.identity_count = 1",
    "      then g.inactive_after_mask else 0 end,",
    "    'originalCommandSha256', case when s.identity_count = 1",
    "      then g.original_command_sha256 else null end,",
    "    'originalCommandMd5', case when s.identity_count = 1",
    "      then g.original_command_md5 else null end,",
    "    'maximumGuardRunId', h.maximum_run_id,",
    "    'maximumGuardSuccessRunId', h.maximum_success_run_id,",
    "    'maximumGuardFailureRunId', h.maximum_failure_run_id,",
    "    'successfulTerminalRunCount', h.successful_terminal_run_count,",
    "    'terminalFailureCount', h.terminal_failure_count,",
    "    'terminalHistoryStartUtc', case when h.terminal_history_start_time is null",
    "      then null else to_char(h.terminal_history_start_time at time zone 'UTC',",
    "        'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') end,",
    "    'terminalHistoryStatus', h.terminal_history_status,",
    "    'maximumAnyDeadmanRunId', d.maximum_run_id,",
    "    'fast', f.sample",
    "  ) as sample",
    "from heartbeat_clock c cross join latest_run l cross join guard_summary s",
    "cross join guard_history h cross join deadman_history d cross join fast_envelope f",
    "left join guard_selected g on true;",
    "",
  ].join("\n")
  if (sha256Text(sql) !== DEADMAN_RECONCILIATION_SQL_SHA256 || !sql.endsWith(";\n")) {
    throw new Error("Dead-man reconciliation SQL is not sealed")
  }
  return sql
}
