import {
  DEADMAN_COMMAND_TAG,
  DEADMAN_GENERATION_PREFIX,
  DEADMAN_TERMINAL_MARKER,
  DEADMAN_TERMINAL_STATUS,
} from "./deadman_command_constants.ts"
import { validateDeadmanCommandInput } from "./validate_deadman_command_input.ts"

export function generateDeadmanCommand(value: unknown): string {
  const input = validateDeadmanCommandInput(value)
  const marker = `${DEADMAN_GENERATION_PREFIX}:${input.runId}:${input.generationSha256}`
  const targets = new Map(input.targetJobs.map((target) => [target.jobId, target]))
  const routing = targets.get(2)!
  const toast = targets.get(3)!
  const legacyProjection = targets.get(4)!
  const databaseProjection = targets.get(11)!
  return [
    `do ${DEADMAN_COMMAND_TAG}`,
    "declare",
    "  guard_job_id bigint;",
    `  guard_run_id bigint := 0;`,
    "  guard_start_at timestamptz;",
    "  current_guard_command text;",
    "  terminal_command text;",
    "  exact_identity_mask integer := 0;",
    "  active_before_mask integer := 0;",
    "  inactive_after_mask integer := 0;",
    "  original_command_sha256 text;",
    "  original_command_md5 text;",
    `  generation_marker constant text := '${marker}';`,
    `  expiry_at constant timestamptz := timestamptz '${input.expiryPlaceholder}';`,
    `  start_cron_run_id constant bigint := ${input.startCronRunId};`,
    "begin",
    "  perform pg_advisory_xact_lock(",
    `    hashtextextended('${input.advisoryLockKey}', 0)`,
    "  );",
    "  select j.jobid, j.command",
    "  into strict guard_job_id, current_guard_command",
    "  from cron.job j",
    `  where j.jobname = '${input.guardName}'`,
    `    and j.schedule = '${input.guardSchedule}';`,
    "  if strpos(current_guard_command, generation_marker) = 0 then",
    "    return;",
    "  end if;",
    "  if clock_timestamp() < expiry_at then",
    "    return;",
    "  end if;",
    "  select",
    "    coalesce(sum(case when case j.jobid",
    `      when 2 then j.jobname = '${routing.jobName}' and`,
    `        j.schedule = '${routing.schedule}' and md5(j.command) = '${routing.commandMd5}'`,
    `      when 3 then j.jobname = '${toast.jobName}' and`,
    `        j.schedule = '${toast.schedule}' and md5(j.command) = '${toast.commandMd5}'`,
    `      when 4 then j.jobname = '${legacyProjection.jobName}' and`,
    `        j.schedule = '${legacyProjection.schedule}' and`,
    `        md5(j.command) = '${legacyProjection.commandMd5}'`,
    `      when 11 then j.jobname = '${databaseProjection.jobName}' and`,
    `        j.schedule = '${databaseProjection.schedule}' and`,
    `        md5(j.command) = '${databaseProjection.commandMd5}'`,
    "      else false end then case j.jobid",
    "        when 2 then 1 when 3 then 2 when 4 then 4 when 11 then 8",
    "        else 0 end else 0 end), 0)::integer,",
    "    coalesce(sum(case when j.active then case j.jobid",
    "      when 2 then 1 when 3 then 2 when 4 then 4 when 11 then 8",
    "      else 0 end else 0 end), 0)::integer",
    "  into exact_identity_mask, active_before_mask",
    "  from cron.job j",
    "  where j.jobid in (2, 3, 4, 11);",
    "  if (exact_identity_mask & 2) = 2 then",
    "    perform cron.alter_job(job_id := 3, active := false);",
    "  end if;",
    "  if (exact_identity_mask & 1) = 1 then",
    "    perform cron.alter_job(job_id := 2, active := false);",
    "  end if;",
    "  if (exact_identity_mask & 8) = 8 then",
    "    perform cron.alter_job(job_id := 11, active := false);",
    "  end if;",
    "  select coalesce(sum(case when not j.active then case j.jobid",
    "    when 2 then 1 when 3 then 2 when 4 then 4 when 11 then 8",
    "    else 0 end else 0 end), 0)::integer",
    "  into inactive_after_mask",
    "  from cron.job j where j.jobid in (2, 3, 4, 11);",
    "  select d.runid, d.start_time",
    "  into guard_run_id, guard_start_at",
    "  from cron.job_run_details d",
    "  where d.jobid = guard_job_id and d.runid > start_cron_run_id",
    "    and d.status = 'running' and d.command = current_guard_command",
    "  order by d.runid desc limit 1;",
    "  guard_run_id := coalesce(guard_run_id, 0);",
    "  guard_start_at := coalesce(guard_start_at, expiry_at - interval '30 seconds');",
    "  original_command_sha256 := encode(extensions.digest(",
    "    convert_to(current_guard_command, 'UTF8'), 'sha256'), 'hex');",
    "  original_command_md5 := md5(current_guard_command);",
    "  terminal_command := format($momi_terminal$select %L::text as marker,",
    "  %L::text as run_id,",
    "  %L::text as generation_sha256,",
    "  %L::text as expiry_utc,",
    "  %s::bigint as guard_run_id,",
    "  %L::text as guard_start_utc,",
    "  %L::text as expected_terminal_status,",
    "  %s::integer as exact_identity_mask,",
    "  %s::integer as active_before_mask,",
    "  %s::integer as inactive_after_mask,",
    "  %L::text as original_command_sha256,",
    "  %L::text as original_command_md5;",
    "$momi_terminal$ ,",
    `    '${DEADMAN_TERMINAL_MARKER}', '${input.runId}', '${input.generationSha256}',`,
    "    to_char(expiry_at at time zone 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"'),",
    "    guard_run_id,",
    "    to_char(guard_start_at at time zone 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"'),",
    `    '${DEADMAN_TERMINAL_STATUS}', exact_identity_mask, active_before_mask,`,
    "    inactive_after_mask, original_command_sha256, original_command_md5);",
    "  perform cron.alter_job(job_id := guard_job_id, command := terminal_command);",
    "  perform cron.alter_job(job_id := guard_job_id, active := false);",
    "end",
    `${DEADMAN_COMMAND_TAG};`,
    "",
  ].join("\n")
}
