import type { FastSample, ResourceSample } from "./sample_types.ts"

export const VALID_FAST_SAMPLE = {
  observedAtUtcMs: Date.UTC(2026, 7, 2, 12, 0, 0),
  activeCronExecutions: 1,
  nonTargetNonGuardActiveExecutions: 0,
  targetJobs: [
    { jobId: 2, jobName: "momi-event-routing-wakeup-v1", schedule: "3 seconds",
      commandMd5: "d1db18b38a3577efa40b514345e960d7", active: false },
    { jobId: 3, jobName: "momi-toast-acquisition-wakeup-v1", schedule: "1 second",
      commandMd5: "2fdbc4715c4d43d48c491f292cd5ce3f", active: false },
    { jobId: 4, jobName: "momi-warehouse-projection-wakeup-v1", schedule: "3 seconds",
      commandMd5: "a01f61a82f58583bf81c20e2a66388fb", active: false },
    { jobId: 11, jobName: "momi-warehouse-projection-database-v1", schedule: "3 seconds",
      commandMd5: "244f8439267e4c7ceedf07d503919f91", active: false },
  ],
  guard: {
    jobName: "momi-issue-330-canary-deadman-v1",
    schedule: "5 seconds",
    active: true,
  },
  targetExecutions: 0,
  targetFailures: 0,
  guardFailures: 0,
  guardRunCount: 0,
  missedSamples: 0,
  overlappingSamples: 0,
  toastReady: 0,
  toastRunning: 0,
  toastRetry: 0,
  toastDead: 0,
  routingReady: 0,
  routingRunning: 0,
  routingRetry: 0,
  routingDead: 0,
  deliveryReady: 0,
  deliveryRunning: 0,
  deliveryRetry: 0,
  deliveryDead: 0,
  queueReady: 0,
  queueDead: 0,
  expiredLeases: 0,
  longLeases: 0,
  openAttempts: 0,
  projectionReservations: 0,
  workerCapViolations: 0,
  waitingLocks: 0,
} satisfies FastSample

export const VALID_RESOURCE_SAMPLE = {
  observedAtUtcMs: Date.UTC(2026, 7, 2, 12, 0, 0),
  activeCronExecutions: 1,
  targetRunCount: 0,
  targetRunFailures: 0,
  guardRunCount: 0,
  guardRunFailures: 0,
  guardCronHistoryEstimatedBytes: 0,
  totalTaskGrowthBytes: 0,
  databaseGrowthBytes: 0,
  cronHistoryGrowthBytes: 0,
  walDirectoryBytes: 855_638_386,
  waitingLocks: 0,
  deadlockDelta: 0,
  databaseBackends: 13,
} satisfies ResourceSample
