export const DRY_RUN_DURATION_SECONDS = 300
export const FAST_SAMPLE_INTERVAL_SECONDS = 15
export const RESOURCE_SAMPLE_INTERVAL_SECONDS = 60
export const MAX_LAUNCH_LATENESS_MS = 250
export const PROVIDER_DEADLINE_MS = 10_000
export const LIFECYCLE_DEADLINE_MS = 12_000
