import { sqlLiteral } from "./sql_literal.ts"

export function buildCompleteSql(importRunId: string): string {
  const run = `${sqlLiteral(importRunId)}::uuid`
  return [
    "-- legacy-recipe-import: import reconciliation",
    "begin;",
    "with counts as (",
    "  select",
    "    (select count(*) from legacy_recipe_staging.source_rows",
    `      where import_run_id = ${run}) as source_rows,`,
    "    (select count(*) from legacy_recipe_staging.repair_findings",
    `      where import_run_id = ${run}) as findings,`,
    "    (select count(*) from legacy_recipe_staging.import_batches",
    `      where import_run_id = ${run} and batch_status = 'applied') as batches`,
    "), updated as (",
    "  update legacy_recipe_staging.import_runs r set",
    "    imported_source_row_count = counts.source_rows,",
    "    imported_finding_count = counts.findings,",
    "    run_status = case when",
    "      counts.source_rows = r.expected_source_row_count",
    "      and counts.findings = r.expected_finding_count",
    "      and counts.batches = r.expected_batch_count",
    "      then 'imported' else 'failed' end,",
    "    completed_at = case when",
    "      counts.source_rows = r.expected_source_row_count",
    "      and counts.findings = r.expected_finding_count",
    "      and counts.batches = r.expected_batch_count then now() else null end,",
    "    failure_count = r.failure_count + case when",
    "      counts.source_rows = r.expected_source_row_count",
    "      and counts.findings = r.expected_finding_count",
    "      and counts.batches = r.expected_batch_count then 0 else 1 end,",
    "    last_error_code = case when",
    "      counts.source_rows = r.expected_source_row_count",
    "      and counts.findings = r.expected_finding_count",
    "      and counts.batches = r.expected_batch_count",
    "      then null else 'import_reconciliation_failed' end,",
    "    last_error_at = case when",
    "      counts.source_rows = r.expected_source_row_count",
    "      and counts.findings = r.expected_finding_count",
    "      and counts.batches = r.expected_batch_count then null else now() end,",
    "    updated_at = now()",
    "  from counts",
    `  where r.import_run_id = ${run}`,
    "  returning r.import_run_id",
    ") select count(*) from updated;",
    "commit;",
    "select jsonb_build_object(",
    "  'legacy_recipe_status', run_status",
    ")::text as legacy_recipe_result",
    "from legacy_recipe_staging.import_runs",
    `where import_run_id = ${run};`,
    "",
  ].join("\n")
}
