export type FunctionManifest = {
  function_key: string
  purpose: string
  owner_service: string
  capability: string
  boundary: string
  runtime: string
  route_path: string
}

const lifecycleOrder = ["ingest", "hydrate", "read", "decide", "deliver"]

export function renderFunctionCatalog(
  manifests: FunctionManifest[],
): string {
  const ordered = [...manifests].sort((left, right) => {
    const capabilityDifference = lifecycleOrder.indexOf(left.capability) -
      lifecycleOrder.indexOf(right.capability)

    return capabilityDifference || left.function_key.localeCompare(
      right.function_key,
    )
  })
  const lines = [
    "# Edge Function Service Catalog",
    "",
    "> Generated by `npm run catalog:generate`. Do not edit by hand.",
    "",
    "Functions are ordered by logical lifecycle capability. Runtime and route",
    "identify deployment location but do not define business purpose.",
    "",
    "| Capability | Function key | Purpose | Boundary | Owner | Runtime | Route |",
    "| --- | --- | --- | --- | --- | --- | --- |",
  ]

  for (const manifest of ordered) {
    lines.push(
      `| ${manifest.capability} | \`${manifest.function_key}\` | ${manifest.purpose} | ` +
        `${manifest.boundary} | \`${manifest.owner_service}\` | ` +
        `${manifest.runtime} | \`${manifest.route_path}\` |`,
    )
  }

  return `${lines.join("\n")}\n`
}
