import type { LoadedFunction, LoadedService } from "./architecture/types.ts"
import { classifyServiceStatus } from
  "./architecture/classify_service_status.ts"

const lifecycleOrder = ["ingest", "hydrate", "read", "decide", "deliver"]

export function renderFunctionCatalog(
  functions: LoadedFunction[],
  services: LoadedService[],
): string {
  const serviceLines = [...services]
    .sort((left, right) => left.manifest.service_key.localeCompare(
      right.manifest.service_key,
    ))
    .map(({ manifest }) => {
      const status = classifyServiceStatus(manifest.implementation_status)
      const provides = [...manifest.contracts.provides].sort()
        .map((contract) => `\`${contract}\``).join(", ") || "none"
      const ownedFunctions = [...manifest.functions].sort()
        .map((slug) => `\`${slug}\``).join(", ") || "none"
      const deployment = [...(manifest.deployment?.owns ?? [])]
        .map((unit) => `${unit.kind}:${unit.key}`).sort()
        .map((unit) => `\`${unit}\``).join(", ") || "none"
      return `| \`${manifest.service_key}\` | ${manifest.lifecycle_status} | ` +
        `${status.implementation} | ${status.availability} | ${provides} | ` +
        `${ownedFunctions} | ${deployment} |`
    })
  const ordered = [...functions].sort((left, right) => {
    const capabilityDifference = lifecycleOrder.indexOf(left.manifest.capability) -
      lifecycleOrder.indexOf(right.manifest.capability)

    return capabilityDifference || left.manifest.function_key.localeCompare(
      right.manifest.function_key,
    )
  })
  const lines = [
    "# Service Catalog",
    "",
    "> Generated by `npm run catalog:generate`. Do not edit by hand.",
    "",
    "## Services",
    "",
    "Availability is derived from implementation status. An absent transitional",
    "implementation status is rendered explicitly and is never inferred.",
    "",
    "| Service | Lifecycle | Implementation | Availability | Provides | Functions | Deployment |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...serviceLines,
    "",
    "## Edge Functions",
    "",
    "Functions are ordered by logical lifecycle capability. Runtime and route",
    "identify deployment location but do not define business purpose.",
    "",
    "| Capability | Function key | Purpose | Service | Kind | Boundary | Route |",
    "| --- | --- | --- | --- | --- | --- | --- |",
  ]

  for (const entry of ordered) {
    const manifest = entry.manifest
    const service = entry.service.manifest
    lines.push(
      `| ${manifest.capability} | \`${manifest.function_key}\` | ${manifest.purpose} | ` +
        `\`${service.service_key}\` | ${service.kind} | ${manifest.boundary} | ` +
        `\`${manifest.route_path}\` |`,
    )
  }

  return `${lines.join("\n")}\n`
}
