-- service-owner: toast-data-acquisition

insert into toast_acquisition.operation_parameters (
  operation_key, parameter_key, parameter_location,
  data_type, required, validation_pattern
) values
  ('toast.orders.bulk.v1', 'startDate', 'query', 'timestamp', false, null),
  ('toast.orders.bulk.v1', 'endDate', 'query', 'timestamp', false, null),
  ('toast.orders.bulk.v1', 'businessDate', 'query', 'date', false, '^[0-9]{8}$'),
  ('toast.orders.bulk.v1', 'pageSize', 'query', 'integer', false, '^(100|[1-9][0-9]?)$'),
  ('toast.orders.bulk.v1', 'page', 'query', 'integer', false, '^[1-9][0-9]*$'),
  ('toast.orders.get.v1', 'guid', 'path', 'string', true, '^[0-9a-fA-F-]+$'),
  ('toast.payments.list.v1', 'paidBusinessDate', 'query', 'date', false, '^[0-9]{8}$'),
  ('toast.payments.list.v1', 'refundBusinessDate', 'query', 'date', false, '^[0-9]{8}$'),
  ('toast.payments.list.v1', 'voidBusinessDate', 'query', 'date', false, '^[0-9]{8}$'),
  ('toast.payments.get.v1', 'guid', 'path', 'string', true, '^[0-9a-fA-F-]+$'),
  ('toast.cash.entries.v1', 'businessDate', 'query', 'date', true, '^[0-9]{8}$'),
  ('toast.cash.deposits.v1', 'businessDate', 'query', 'date', true, '^[0-9]{8}$'),
  ('toast.restaurants.group.v1', 'managementGroupGUID', 'path', 'string', true, '^[0-9a-fA-F-]+$'),
  ('toast.restaurants.get.v1', 'restaurantGUID', 'path', 'string', true, '^[0-9a-fA-F-]+$'),
  ('toast.restaurants.get.v1', 'includeArchived', 'query', 'boolean', false, '^(true|false)$'),
  ('toast.kitchen.fulfillments.v1', 'businessDate', 'query', 'date', true, '^[0-9]{8}$'),
  ('toast.kitchen.prep_stations.v1', 'pageToken', 'query', 'string', false, null),
  ('toast.kitchen.prep_stations.v1', 'lastModified', 'query', 'timestamp', false, null),
  ('toast.kitchen.prep_station.v1', 'guid', 'path', 'string', true, '^[0-9a-fA-F-]+$'),
  ('toast.labor.employee.v1', 'employeeId', 'path', 'string', true, '^[0-9a-fA-F-]+$'),
  ('toast.labor.job.v1', 'jobId', 'path', 'string', true, '^[0-9a-fA-F-]+$'),
  ('toast.labor.shifts.v1', 'shiftIds', 'query', 'string', false, null),
  ('toast.labor.shifts.v1', 'startDate', 'query', 'timestamp', false, null),
  ('toast.labor.shifts.v1', 'endDate', 'query', 'timestamp', false, null),
  ('toast.labor.shift.v1', 'shiftId', 'path', 'string', true, '^[0-9a-fA-F-]+$'),
  ('toast.labor.time_entries.v1', 'timeEntryIds', 'query', 'string', false, null),
  ('toast.labor.time_entries.v1', 'startDate', 'query', 'timestamp', false, null),
  ('toast.labor.time_entries.v1', 'endDate', 'query', 'timestamp', false, null),
  ('toast.labor.time_entries.v1', 'modifiedStartDate', 'query', 'timestamp', false, null),
  ('toast.labor.time_entries.v1', 'modifiedEndDate', 'query', 'timestamp', false, null),
  ('toast.labor.time_entries.v1', 'businessDate', 'query', 'date', false, '^[0-9]{8}$'),
  ('toast.labor.time_entries.v1', 'includeArchived', 'query', 'boolean', false, '^(true|false)$'),
  ('toast.labor.time_entries.v1', 'includeMissedBreaks', 'query', 'boolean', false, '^(true|false)$'),
  ('toast.labor.time_entry.v1', 'timeEntryId', 'path', 'string', true, '^[0-9a-fA-F-]+$'),
  ('toast.stock.snapshot.v1', 'status', 'query', 'string', false, '^(OUT_OF_STOCK|QUANTITY)$');
